fixup! fixup! [CI] WIP

diff --git a/.github/workflows/common.yml b/.github/workflows/common.yml
--- a/.github/workflows/common.yml
+++ b/.github/workflows/common.yml
@@ -263,15 +263,18 @@ jobs:
         if: "runner.os == 'Windows' && inputs.cygwin"
 
       - name: Install OCaml compiler ${{ env.COMPILER }} (Cygwin)
-        shell: bash
+        env:
+          REPODIR: ${{ github.workspace }}
         run: |
-          opam init --disable-sandboxing --auto-setup --bare                                            #
-          opam repository add --all main "https://github.com/ocaml/opam-repository.git"                 #
-          opam repository add --all windows "https://github.com/fdopen/opam-repository-mingw.git#opam2" #
-          opam repository add --all override "https://github.com/shym/custom-opam-repository.git"       #
-          opam repository add --all dra27 "https://github.com/dra27/opam-repository.git#windows-5.0"    #
-          opam repository add --all local "./.github/opam/custom"                                       #
-          opam switch create default --repositories=dra27,override,windows,main --packages "$COMPILER"  #
+          opam init --disable-sandboxing --auto-setup --bare
+          opam repository add --all main "https://github.com/ocaml/opam-repository.git"
+          opam repository add --all windows "https://github.com/fdopen/opam-repository-mingw.git#opam2"
+          opam repository add --all override "https://github.com/shym/custom-opam-repository.git"
+          opam repository add --all dra27 "https://github.com/dra27/opam-repository.git#windows-5.0"
+          echo "Adding ${env:REPODIR}"
+          Get-Item "${env:REPODIR}\*"
+          opam repository add --all local "file://${env:REPODIR}\.github\opam\custom"
+          opam switch create default --repositories=dra27,override,windows,main --packages "${env:COMPILER}"
         if: "runner.os == 'Windows' && inputs.cygwin && steps.cache_opam.outputs.cache-hit != 'true'"
 
       - name: Set up macOS environment ($OPAMJOBS)
@@ -322,28 +325,28 @@ jobs:
       - name: Run only one test
         shell: bash
         run: |
-          failures=0                                                          #
-          for i in `seq "$REPEATS"`; do                                       #
-            echo                                                              #
-            echo "Starting $i-th run"                                         #
-            if [ -n "$SEED" ]; then                                           #
-              if ! opam exec -- dune exec "$ONLY_TEST" -- -v -s "$SEED"; then #
-                if [ "$REPEATS_FAILFAST" = "true" ]; then                     #
-                  exit 1                                                      #
-                else                                                          #
-                  failures=$((failures + 1))                                  #
-                fi                                                            #
-              fi                                                              #
-            else                                                              #
-              if ! opam exec -- dune exec "$ONLY_TEST" -- -v; then            #
-                if [ "$REPEATS_FAILFAST" = "true" ]; then                     #
-                  exit 1                                                      #
-                else                                                          #
-                  failures=$((failures + 1))                                  #
-                fi                                                            #
-              fi                                                              #
-            fi                                                                #
-          done                                                                #
-          echo "Test failed $failures times"                                  #
-          [ "$failures" = 0 ]                                                 #
+          failures=0
+          for i in `seq "$REPEATS"`; do
+            echo
+            echo "Starting $i-th run"
+            if [ -n "$SEED" ]; then
+              if ! opam exec -- dune exec "$ONLY_TEST" -- -v -s "$SEED"; then
+                if [ "$REPEATS_FAILFAST" = "true" ]; then
+                  exit 1
+                else
+                  failures=$((failures + 1))
+                fi
+              fi
+            else
+              if ! opam exec -- dune exec "$ONLY_TEST" -- -v; then
+                if [ "$REPEATS_FAILFAST" = "true" ]; then
+                  exit 1
+                else
+                  failures=$((failures + 1))
+                fi
+              fi
+            fi
+          done
+          echo "Test failed $failures times"
+          [ "$failures" = 0 ]
         if: env.ONLY_TEST != ''
