CI: Add a repeats_failfast inputs
When some test is repeating just to see whether it fails, end the tests
as soon as we know

diff --git a/.github/workflows/common.yml b/.github/workflows/common.yml
--- a/.github/workflows/common.yml
+++ b/.github/workflows/common.yml
@@ -31,6 +31,10 @@ on:
         description: 'Number of test attempts'
         type: string
         default: '10'
+      repeats_failfast:
+        description: 'When repeating a test, stop as soon as one test fails'
+        type: boolean
+        default: false
       compiler_commit:
         description: 'Version (commit) of the OCaml compiler to use'
         type: string
@@ -44,6 +48,7 @@ jobs:
       REPEATS: ${{ inputs.repeats }}
       OCAML_COMPILER_COMMIT: ${{ inputs.compiler_commit }}
       OCAML_COMPILER_BRANCH: ${{ inputs.compiler_branch }}
+      REPEATS_FAILFAST: ${{ inputs.repeats_failfast }}
 
     runs-on: ${{ inputs.runs_on }}
 
@@ -109,12 +114,25 @@ jobs:
 
       - name: Run only one test
         run: |
+          echo "REPEATS_FAILFAST: $REPEATS_FAILFAST"
           failures=0
           for i in `seq "$REPEATS"`; do
             if [ -n "$SEED" ]; then
-              opam exec -- dune exec "$ONLY_TEST" -- -v -s "$SEED" || failures=$((failures + 1))
+              if ! opam exec -- dune exec "$ONLY_TEST" -- -v -s "$SEED"; then
+                if [ "$REPEATS_FAILFAST" = "true" ]; then
+                  exit 1
+                else
+                  failures=$((failures + 1))
+                fi
+              fi
             else
-              opam exec -- dune exec "$ONLY_TEST" -- -v || failures=$((failures + 1))
+              if ! opam exec -- dune exec "$ONLY_TEST" -- -v; then
+                if [ "$REPEATS_FAILFAST" = "true" ]; then
+                  exit 1
+                else
+                  failures=$((failures + 1))
+                fi
+              fi
             fi
           done
           echo "Test failed $failures times"
